#!/bin/bash
#SBATCH -t 90:00:00
#SBATCH -o ./sbatchlog/slurm-%j.out
#SBATCH -c 8
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --array=0-126%12
#SBATCH --partition=compsci-gpu
#SBATCH --array=0-126%12

IFS=$'\n' read -d '' -r -a lines < jobs.txt
echo "Starting task $SLURM_ARRAY_TASK_ID: ${lines[SLURM_ARRAY_TASK_ID]}"
eval ${lines[SLURM_ARRAY_TASK_ID]}
